# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Small Sewer Hydraulic Analysis
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://adams-cool-org.github.io
baseurl:          ssha3

author:
  name:           'PWD Planning and Research'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pwdpr/ssha
