# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Small Sewer Hydraulic Analysis
tagline:          'A Jekyll theme'
description:      'Standard operating procedure for Small Sewer Hydraulic Analysis'
url:              https://adams-cool-org.github.io
baseurl:          /ssha3

author:
  name:           'PWD Planning and Research'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pwdpr/ssha
